name: Changelog

on:
  release:
    types: [prereleased, released]

jobs:
  changelog:

    runs-on: ubuntu-latest

    steps:
      - name: Export Properties
        id: properties
        shell: bash
        run: |
          CHANGELOG="$(cat << 'EOM' |  sed '/^-/!d;s/- #[[:digit:]]\+ \(.*\) @\(.*\)/- \1/g' | sed -e 's/^[[:space:]]*$//g' -e '/./,$!d'
          ${{ github.event.release.body }}
          EOM
          )"
          echo "$CHANGELOG"
