on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

name: Create Release

jobs:
  output:
    runs-on: ubuntu-latest

    steps:
    - name: Create release
      run: echo "Create Release ${{ github.ref }}"

