name: Write File
on:
  workflow_dispatch:
  
jobs:
  write:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare file
        run: echo "${{ secrets.file_content_b64 }}" | base64 --decode > file
          
      - name: Use file
        run: bash echo :securesmsproxyapi:publish --stacktrace -Psignatory.keyId=key_id -Psigning.password="passphrase" -Psigning.secretKeyRingFile=file -PossUsername=nexus_username -PossPassword="secrets.nexus_password"    
          
