name: Write File
on:
  workflow_dispatch:
  
jobs:
  write:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare file
        run: echo "${{ secrets.file_content_b64 }}" | base64 --decode > file
          
      - name: Use file
        run: echo :securesmsproxyapi:publish --stacktrace -Psignatory.keyId=ABCD -Psigning.password="xx;fd'zh^9" -Psigning.secretKeyRingFile=file -PossUsername=nexus_username -PossPassword="xx;fdzh"
          
